version: '3.8'

services:
  app:
    build: .
    container_name: sedim-app
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - sedim-network

networks:
  sedim-network:
    driver: bridge
