-- Fase 22: solo tablas nuevas. No modificar tablas descargadas ni Cocina_pedidos.
IF OBJECT_ID('dbo.Pedido_control','U') IS NULL
CREATE TABLE dbo.Pedido_control (NroTicket VARCHAR(20) NOT NULL PRIMARY KEY, Empresa INT NOT NULL, Version INT NOT NULL DEFAULT 0, UltimoEnvio INT NOT NULL DEFAULT 0, SnapshotComercial NVARCHAR(MAX) NOT NULL DEFAULT '[]');
IF OBJECT_ID('dbo.Pedido_lineas','U') IS NULL
CREATE TABLE dbo.Pedido_lineas (LineaId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, NroTicket VARCHAR(20) NOT NULL, Orden INT NOT NULL, Datos NVARCHAR(MAX) NOT NULL CHECK (ISJSON(Datos)=1), Baja BIT NOT NULL DEFAULT 0, Enviada NVARCHAR(MAX) NULL CHECK (Enviada IS NULL OR ISJSON(Enviada)=1), CONSTRAINT FK_Pedido_lineas_control FOREIGN KEY (NroTicket) REFERENCES dbo.Pedido_control(NroTicket));
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_Pedido_lineas_ticket' AND object_id=OBJECT_ID('dbo.Pedido_lineas')) CREATE INDEX IX_Pedido_lineas_ticket ON dbo.Pedido_lineas(NroTicket, Orden);
IF OBJECT_ID('dbo.Cocina_envios','U') IS NULL
CREATE TABLE dbo.Cocina_envios (Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, NroTicket VARCHAR(20) NOT NULL, Numero INT NOT NULL, Clave UNIQUEIDENTIFIER NOT NULL, Version INT NOT NULL, Cabecera NVARCHAR(MAX) NOT NULL CHECK (ISJSON(Cabecera)=1), Documento NVARCHAR(MAX) NOT NULL, Fecha DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), Historico BIT NOT NULL DEFAULT 0, CONSTRAINT FK_Cocina_envios_control FOREIGN KEY(NroTicket) REFERENCES dbo.Pedido_control(NroTicket), CONSTRAINT UQ_Cocina_envio_numero UNIQUE(NroTicket,Numero), CONSTRAINT UQ_Cocina_envio_clave UNIQUE(NroTicket,Clave));
IF OBJECT_ID('dbo.Cocina_envio_detalles','U') IS NULL
CREATE TABLE dbo.Cocina_envio_detalles (Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, EnvioId UNIQUEIDENTIFIER NOT NULL, LineaId UNIQUEIDENTIFIER NOT NULL, Movimiento NVARCHAR(MAX) NOT NULL CHECK(ISJSON(Movimiento)=1), ReconocidoPor NVARCHAR(50) NULL, ReconocidoFecha DATETIME2 NULL, CONSTRAINT FK_Cocina_det_envio FOREIGN KEY(EnvioId) REFERENCES dbo.Cocina_envios(Id), CONSTRAINT FK_Cocina_det_linea FOREIGN KEY(LineaId) REFERENCES dbo.Pedido_lineas(LineaId));
IF OBJECT_ID('dbo.Cocina_estados','U') IS NULL
CREATE TABLE dbo.Cocina_estados (LineaId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, NroTicket VARCHAR(20) NOT NULL, Codpro CHAR(10) NOT NULL, Estado INT NOT NULL DEFAULT 1 CHECK(Estado BETWEEN 1 AND 4), Operativa NVARCHAR(MAX) NOT NULL CHECK(ISJSON(Operativa)=1), PendienteId UNIQUEIDENTIFIER NULL, Anulada BIT NOT NULL DEFAULT 0, FechaEnvio DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), FechaEstado DATETIME2 NULL, Usuario NVARCHAR(50) NULL, CONSTRAINT FK_Cocina_est_control FOREIGN KEY(NroTicket) REFERENCES dbo.Pedido_control(NroTicket), CONSTRAINT FK_Cocina_est_pendiente FOREIGN KEY(PendienteId) REFERENCES dbo.Cocina_envio_detalles(Id));
IF OBJECT_ID('dbo.Impresion_trabajos','U') IS NULL
CREATE TABLE dbo.Impresion_trabajos (Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, EnvioId UNIQUEIDENTIFIER NOT NULL, ReimpresionDe UNIQUEIDENTIFIER NULL, Clave UNIQUEIDENTIFIER NOT NULL UNIQUE, Documento NVARCHAR(MAX) NOT NULL, Estado VARCHAR(24) NOT NULL DEFAULT 'en_cola' CHECK(Estado IN('en_cola','procesando','enviado','error','incierto')), Intentos INT NOT NULL DEFAULT 0, Error NVARCHAR(1000) NULL, Usuario NVARCHAR(50) NOT NULL, Fecha DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), Actualizado DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), ProximoIntento DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT FK_Impresion_envio FOREIGN KEY(EnvioId) REFERENCES dbo.Cocina_envios(Id), CONSTRAINT FK_Impresion_reprint FOREIGN KEY(ReimpresionDe) REFERENCES dbo.Impresion_trabajos(Id));
IF OBJECT_ID('dbo.Cocina_pedidos_legacy','U') IS NULL SELECT TOP (0) * INTO dbo.Cocina_pedidos_legacy FROM dbo.Cocina_pedidos;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_Cocina_envio_detalles_envio' AND object_id=OBJECT_ID('dbo.Cocina_envio_detalles')) CREATE INDEX IX_Cocina_envio_detalles_envio ON dbo.Cocina_envio_detalles(EnvioId);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_Impresion_trabajos_cola' AND object_id=OBJECT_ID('dbo.Impresion_trabajos')) CREATE INDEX IX_Impresion_trabajos_cola ON dbo.Impresion_trabajos(Estado,ProximoIntento);
